# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(812, 667)
        self.TabWidget_BPNetwork = QtWidgets.QTabWidget(Form)
        self.TabWidget_BPNetwork.setGeometry(QtCore.QRect(0, 0, 811, 661))
        self.TabWidget_BPNetwork.setObjectName("TabWidget_BPNetwork")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 60, 16))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 571, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PushButton_y_trainPath_BP = QtWidgets.QPushButton(self.layoutWidget)
        self.PushButton_y_trainPath_BP.setObjectName("PushButton_y_trainPath_BP")
        self.gridLayout.addWidget(self.PushButton_y_trainPath_BP, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lineEdit_y_trainPath_BP = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_y_trainPath_BP.setObjectName("lineEdit_y_trainPath_BP")
        self.gridLayout.addWidget(self.lineEdit_y_trainPath_BP, 2, 1, 1, 2)
        self.lineEdit_xVaribleNumber_BP = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_xVaribleNumber_BP.setObjectName("lineEdit_xVaribleNumber_BP")
        self.gridLayout.addWidget(self.lineEdit_xVaribleNumber_BP, 3, 1, 1, 2)
        self.PushButton_x_trainPath_BP = QtWidgets.QPushButton(self.layoutWidget)
        self.PushButton_x_trainPath_BP.setObjectName("PushButton_x_trainPath_BP")
        self.gridLayout.addWidget(self.PushButton_x_trainPath_BP, 0, 0, 2, 1)
        self.lineEdit_x_trainPath_BP = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_x_trainPath_BP.setObjectName("lineEdit_x_trainPath_BP")
        self.gridLayout.addWidget(self.lineEdit_x_trainPath_BP, 0, 1, 2, 2)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(180, 270, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(570, 270, 72, 15))
        self.label_4.setObjectName("label_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 300, 781, 321))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_zi_bian_liang = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_zi_bian_liang.setObjectName("tableWidget_zi_bian_liang")
        self.tableWidget_zi_bian_liang.setColumnCount(0)
        self.tableWidget_zi_bian_liang.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_zi_bian_liang)
        self.tableWidget_yin_bian_liang = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_yin_bian_liang.setObjectName("tableWidget_yin_bian_liang")
        self.tableWidget_yin_bian_liang.setColumnCount(0)
        self.tableWidget_yin_bian_liang.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_yin_bian_liang)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(640, 70, 95, 161))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_xian_shi_shu_ju = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_xian_shi_shu_ju.setObjectName("pushButton_xian_shi_shu_ju")
        self.verticalLayout.addWidget(self.pushButton_xian_shi_shu_ju)
        self.PushButton_Next_ReadData_BP = QtWidgets.QPushButton(self.layoutWidget2)
        self.PushButton_Next_ReadData_BP.setObjectName("PushButton_Next_ReadData_BP")
        self.verticalLayout.addWidget(self.PushButton_Next_ReadData_BP)
        self.TabWidget_BPNetwork.addTab(self.tab, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setGeometry(QtCore.QRect(250, 40, 301, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.PushButton_Next_Network_BP = QtWidgets.QPushButton(self.tab_1)
        self.PushButton_Next_Network_BP.setGeometry(QtCore.QRect(670, 570, 113, 32))
        self.PushButton_Next_Network_BP.setObjectName("PushButton_Next_Network_BP")
        self.PushButton_NetworkDelete_BP = QtWidgets.QPushButton(self.tab_1)
        self.PushButton_NetworkDelete_BP.setGeometry(QtCore.QRect(490, 490, 91, 32))
        self.PushButton_NetworkDelete_BP.setObjectName("PushButton_NetworkDelete_BP")
        self.PushButton_NetworkAdd_BP = QtWidgets.QPushButton(self.tab_1)
        self.PushButton_NetworkAdd_BP.setGeometry(QtCore.QRect(600, 490, 91, 32))
        self.PushButton_NetworkAdd_BP.setObjectName("PushButton_NetworkAdd_BP")
        self.TabWidget_BPNetwork.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.PushButton_Next_Optimizer_BP = QtWidgets.QPushButton(self.tab_2)
        self.PushButton_Next_Optimizer_BP.setGeometry(QtCore.QRect(660, 560, 113, 32))
        self.PushButton_Next_Optimizer_BP.setObjectName("PushButton_Next_Optimizer_BP")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(230, 230, 341, 121))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_LearningRate_BP = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_LearningRate_BP.setObjectName("lineEdit_LearningRate_BP")
        self.gridLayout_3.addWidget(self.lineEdit_LearningRate_BP, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 1, 1, 1)
        self.comboBox_lossFunction_BP = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_lossFunction_BP.setObjectName("comboBox_lossFunction_BP")
        self.comboBox_lossFunction_BP.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_lossFunction_BP, 1, 2, 1, 1)
        self.TabWidget_BPNetwork.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.PushButton_Next_Run_BP = QtWidgets.QPushButton(self.tab_3)
        self.PushButton_Next_Run_BP.setGeometry(QtCore.QRect(660, 560, 113, 32))
        self.PushButton_Next_Run_BP.setObjectName("PushButton_Next_Run_BP")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(170, 230, 501, 123))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_Epoch_BP = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_Epoch_BP.setObjectName("lineEdit_Epoch_BP")
        self.gridLayout_4.addWidget(self.lineEdit_Epoch_BP, 0, 1, 1, 1)
        self.pushButton_startTraining_BP = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_startTraining_BP.setObjectName("pushButton_startTraining_BP")
        self.gridLayout_4.addWidget(self.pushButton_startTraining_BP, 1, 0, 1, 1)
        self.textBrowser_trainprogress = QtWidgets.QTextBrowser(self.layoutWidget4)
        self.textBrowser_trainprogress.setObjectName("textBrowser_trainprogress")
        self.gridLayout_4.addWidget(self.textBrowser_trainprogress, 1, 1, 1, 1)
        self.TabWidget_BPNetwork.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(260, 180, 301, 201))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_PredictxVariablePath_BP = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_PredictxVariablePath_BP.setObjectName("pushButton_PredictxVariablePath_BP")
        self.gridLayout_5.addWidget(self.pushButton_PredictxVariablePath_BP, 0, 0, 1, 1)
        self.lineEdit_PredictxVariablePath_BP = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_PredictxVariablePath_BP.setObjectName("lineEdit_PredictxVariablePath_BP")
        self.gridLayout_5.addWidget(self.lineEdit_PredictxVariablePath_BP, 0, 1, 1, 1)
        self.PushButton_ExportPredictData_BP = QtWidgets.QPushButton(self.layoutWidget5)
        self.PushButton_ExportPredictData_BP.setObjectName("PushButton_ExportPredictData_BP")
        self.gridLayout_5.addWidget(self.PushButton_ExportPredictData_BP, 3, 0, 1, 1)
        self.PushButton_ExportTrainHistoryData_BP = QtWidgets.QPushButton(self.layoutWidget5)
        self.PushButton_ExportTrainHistoryData_BP.setObjectName("PushButton_ExportTrainHistoryData_BP")
        self.gridLayout_5.addWidget(self.PushButton_ExportTrainHistoryData_BP, 3, 1, 1, 1)
        self.pushButton_PredictDataPath_BP = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_PredictDataPath_BP.setObjectName("pushButton_PredictDataPath_BP")
        self.gridLayout_5.addWidget(self.pushButton_PredictDataPath_BP, 1, 0, 1, 1)
        self.lineEdit_PredictHistoryPath_BP = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_PredictHistoryPath_BP.setObjectName("lineEdit_PredictHistoryPath_BP")
        self.gridLayout_5.addWidget(self.lineEdit_PredictHistoryPath_BP, 2, 1, 1, 1)
        self.lineEdit_PredictDataPath_BP = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_PredictDataPath_BP.setObjectName("lineEdit_PredictDataPath_BP")
        self.gridLayout_5.addWidget(self.lineEdit_PredictDataPath_BP, 1, 1, 1, 1)
        self.pushButton_PredictHistoryPath_BP = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_PredictHistoryPath_BP.setObjectName("pushButton_PredictHistoryPath_BP")
        self.gridLayout_5.addWidget(self.pushButton_PredictHistoryPath_BP, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(640, 540, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.TabWidget_BPNetwork.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.TabWidget_BPNetwork.setCurrentIndex(0)
        self.pushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "读取数据"))
        self.PushButton_y_trainPath_BP.setText(_translate("Form", "因变量地址"))
        self.label.setText(_translate("Form", "自变量数量"))
        self.PushButton_x_trainPath_BP.setText(_translate("Form", "自变量地址"))
        self.label_3.setText(_translate("Form", "自变量"))
        self.label_4.setText(_translate("Form", "因变量"))
        self.pushButton_xian_shi_shu_ju.setText(_translate("Form", "显示数据"))
        self.PushButton_Next_ReadData_BP.setText(_translate("Form", "下一步"))
        self.TabWidget_BPNetwork.setTabText(self.TabWidget_BPNetwork.indexOf(self.tab), _translate("Form", "读取数据"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "网络层名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "节点数量"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "激活函数"))
        self.PushButton_Next_Network_BP.setText(_translate("Form", "下一步"))
        self.PushButton_NetworkDelete_BP.setText(_translate("Form", "Delete"))
        self.PushButton_NetworkAdd_BP.setText(_translate("Form", "Add"))
        self.TabWidget_BPNetwork.setTabText(self.TabWidget_BPNetwork.indexOf(self.tab_1), _translate("Form", "网络结构"))
        self.PushButton_Next_Optimizer_BP.setText(_translate("Form", "下一步"))
        self.label_5.setText(_translate("Form", "训练速度lr"))
        self.label_6.setText(_translate("Form", "损失函数选择"))
        self.comboBox_lossFunction_BP.setItemText(0, _translate("Form", "mean_squared_error"))
        self.TabWidget_BPNetwork.setTabText(self.TabWidget_BPNetwork.indexOf(self.tab_2), _translate("Form", "优化器"))
        self.PushButton_Next_Run_BP.setText(_translate("Form", "下一步"))
        self.label_7.setText(_translate("Form", "迭代次数"))
        self.pushButton_startTraining_BP.setText(_translate("Form", "开始训练"))
        self.TabWidget_BPNetwork.setTabText(self.TabWidget_BPNetwork.indexOf(self.tab_3), _translate("Form", "运行"))
        self.pushButton_PredictxVariablePath_BP.setText(_translate("Form", "预测自变量地址"))
        self.PushButton_ExportPredictData_BP.setText(_translate("Form", "输出预测数据"))
        self.PushButton_ExportTrainHistoryData_BP.setText(_translate("Form", "输出训练历史数据"))
        self.pushButton_PredictDataPath_BP.setText(_translate("Form", "预测数据输出地址"))
        self.pushButton_PredictHistoryPath_BP.setText(_translate("Form", "训练历史输出地址"))
        self.pushButton.setText(_translate("Form", "关闭"))
        self.TabWidget_BPNetwork.setTabText(self.TabWidget_BPNetwork.indexOf(self.tab_4), _translate("Form", "输出数据"))

