# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_STS.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(802, 654)
        self.tabWidget_sts = QtWidgets.QTabWidget(Form)
        self.tabWidget_sts.setGeometry(QtCore.QRect(0, 0, 801, 651))
        self.tabWidget_sts.setObjectName("tabWidget_sts")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(160, 160, 71, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(580, 160, 71, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_next_dataRead_STS = QtWidgets.QPushButton(self.tab)
        self.pushButton_next_dataRead_STS.setGeometry(QtCore.QRect(680, 590, 113, 32))
        self.pushButton_next_dataRead_STS.setObjectName("pushButton_next_dataRead_STS")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 781, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_mainDataTable_STS = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_mainDataTable_STS.setObjectName("tableWidget_mainDataTable_STS")
        self.tableWidget_mainDataTable_STS.setColumnCount(0)
        self.tableWidget_mainDataTable_STS.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_mainDataTable_STS)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 511, 68))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_readMainData_STS = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_readMainData_STS.setObjectName("pushButton_readMainData_STS")
        self.gridLayout.addWidget(self.pushButton_readMainData_STS, 0, 0, 1, 1)
        self.lineEdit_readMainData_STS = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_readMainData_STS.setObjectName("lineEdit_readMainData_STS")
        self.gridLayout.addWidget(self.lineEdit_readMainData_STS, 0, 1, 1, 1)
        self.pushButton_readConvData_STS = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_readConvData_STS.setObjectName("pushButton_readConvData_STS")
        self.gridLayout.addWidget(self.pushButton_readConvData_STS, 1, 0, 1, 1)
        self.lineEdit_readConvData_STS = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_readConvData_STS.setObjectName("lineEdit_readConvData_STS")
        self.gridLayout.addWidget(self.lineEdit_readConvData_STS, 1, 1, 1, 1)
        self.pushButton_showData = QtWidgets.QPushButton(self.tab)
        self.pushButton_showData.setGeometry(QtCore.QRect(600, 70, 93, 28))
        self.pushButton_showData.setObjectName("pushButton_showData")
        self.tabWidget_sts.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_seasonalModule_STS = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_seasonalModule_STS.setGeometry(QtCore.QRect(240, 100, 301, 361))
        self.tableWidget_seasonalModule_STS.setObjectName("tableWidget_seasonalModule_STS")
        self.tableWidget_seasonalModule_STS.setColumnCount(3)
        self.tableWidget_seasonalModule_STS.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seasonalModule_STS.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seasonalModule_STS.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seasonalModule_STS.setHorizontalHeaderItem(2, item)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(250, 60, 101, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_next_moduleStructure_STS = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_next_moduleStructure_STS.setGeometry(QtCore.QRect(670, 580, 113, 32))
        self.pushButton_next_moduleStructure_STS.setObjectName("pushButton_next_moduleStructure_STS")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 470, 366, 39))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_ARModuleIf_STS = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_ARModuleIf_STS.setObjectName("checkBox_ARModuleIf_STS")
        self.horizontalLayout_2.addWidget(self.checkBox_ARModuleIf_STS)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_addModule_STS = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_addModule_STS.setObjectName("pushButton_addModule_STS")
        self.gridLayout_2.addWidget(self.pushButton_addModule_STS, 0, 0, 1, 1)
        self.pushButton_deleteModule_STS = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_deleteModule_STS.setObjectName("pushButton_deleteModule_STS")
        self.gridLayout_2.addWidget(self.pushButton_deleteModule_STS, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget_sts.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_modelPrint_STS = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_modelPrint_STS.setGeometry(QtCore.QRect(140, 250, 113, 32))
        self.pushButton_modelPrint_STS.setObjectName("pushButton_modelPrint_STS")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(310, 71, 381, 401))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_next_modelPrint_STS = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_next_modelPrint_STS.setGeometry(QtCore.QRect(670, 580, 113, 32))
        self.pushButton_next_modelPrint_STS.setObjectName("pushButton_next_modelPrint_STS")
        self.tabWidget_sts.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_trainModel_STS = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_trainModel_STS.setGeometry(QtCore.QRect(330, 140, 113, 32))
        self.pushButton_trainModel_STS.setObjectName("pushButton_trainModel_STS")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_14.setGeometry(QtCore.QRect(670, 580, 113, 32))
        self.pushButton_14.setObjectName("pushButton_14")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(180, 203, 411, 221))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_numberPredict_STS = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_numberPredict_STS.setObjectName("lineEdit_numberPredict_STS")
        self.gridLayout_3.addWidget(self.lineEdit_numberPredict_STS, 0, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 3, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(190, 90, 391, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.tabWidget_sts.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget_sts.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "主变量数据"))
        self.label_2.setText(_translate("Form", "协变量数据"))
        self.pushButton_next_dataRead_STS.setText(_translate("Form", "下一步"))
        self.pushButton_readMainData_STS.setText(_translate("Form", "读取主变量数据"))
        self.pushButton_readConvData_STS.setText(_translate("Form", "读取协变量数据"))
        self.pushButton_showData.setText(_translate("Form", "显示数据"))
        self.tabWidget_sts.setTabText(self.tabWidget_sts.indexOf(self.tab), _translate("Form", "数据读取"))
        item = self.tableWidget_seasonalModule_STS.horizontalHeaderItem(0)
        item.setText(_translate("Form", "新建列"))
        item = self.tableWidget_seasonalModule_STS.horizontalHeaderItem(1)
        item.setText(_translate("Form", "季节步"))
        item = self.tableWidget_seasonalModule_STS.horizontalHeaderItem(2)
        item.setText(_translate("Form", "子块季节步"))
        self.label_3.setText(_translate("Form", "季节性模块部分"))
        self.pushButton_next_moduleStructure_STS.setText(_translate("Form", "下一步"))
        self.checkBox_ARModuleIf_STS.setText(_translate("Form", "是否启动自回归模块"))
        self.pushButton_addModule_STS.setText(_translate("Form", "添加"))
        self.pushButton_deleteModule_STS.setText(_translate("Form", "减少"))
        self.tabWidget_sts.setTabText(self.tabWidget_sts.indexOf(self.tab_2), _translate("Form", "网络结构"))
        self.pushButton_modelPrint_STS.setText(_translate("Form", "模型打印"))
        self.pushButton_next_modelPrint_STS.setText(_translate("Form", "下一步"))
        self.tabWidget_sts.setTabText(self.tabWidget_sts.indexOf(self.tab_3), _translate("Form", "模型打印"))
        self.pushButton_trainModel_STS.setText(_translate("Form", "开始训练"))
        self.pushButton_14.setText(_translate("Form", "关闭"))
        self.label_4.setText(_translate("Form", "预测数据个数"))
        self.pushButton_11.setText(_translate("Form", "选择输出预测数据地址"))
        self.pushButton_10.setText(_translate("Form", "选择输出训练历史loss地址"))
        self.pushButton_12.setText(_translate("Form", "输出预测数据地址"))
        self.pushButton_13.setText(_translate("Form", "输出历史loss地址"))
        self.label_5.setText(_translate("Form", "迭代次数"))
        self.tabWidget_sts.setTabText(self.tabWidget_sts.indexOf(self.tab_4), _translate("Form", "模型训练"))

